config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products, only: [:show, :index, :create, :update, :destroy]
    end
  end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'
  post '/contact_submit' => 'welcome#contact_submit'

  namespace :admin do
    resources :dashboard, only: [:index]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # get '/products' => 'products#index'
  # delete '/questions/:id' => 'products#destroy'
  # get '/questions/:id/edit' => 'products#edit'
  # get '/questions/:id' => 'products#show'
  # post '/questions/:id/comments' => 'comments#create'

  get '/faq' =>'home#faq'

  # get '/admin/products' => 'admin/products#index'

  # get '/products/new'   => 'products#new', as: :new_product
  # post '/products'      => 'products#create', as: :products
  # get '/products/:id'   => 'products#show', as: :product
  # get '/products'       => 'products#index'
  #
  #
  # delete '/products/:id' => 'products#destroy'
  #
  #
  # get '/product/:id/edit' => 'products#edit', as: :edit_product
  #
  # patch '/products/:id' => 'products#update'

  resources :products, shallow: true do
    resources :reviews, only:[:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only:[:new, :create, :show]

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.all
    @tags = Tag.all
  end

  def contact
  end

  def about
  end

  def contact_submit
    @name = params[:name]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>about</h1>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>


<%= form_tag contact_submit_path do %>
<%= text_field_tag :name %>
<%= email_field_tag :email %>
<%= text_field_tag :message %>
<%= submit_tag 'Contact Us' %>
<% end  %>

app/views/welcome/contact_submit.html.erb
<h1> Thank you <%= @name %> for contacting us</h1>

app/views/welcome/index.html.erb
<h1>Amazon</h1>
<%= link_to('Products', products_path) %>
<%= link_to('New Product', new_product_path) %>

<hr>
<h2>Categories</h2>
<% @categories.each do |q| %>
<%= link_to q.name, products_path(category: q) %>
<% end %>

<h2>Tags</h2>
<% @tags.each do |q| %>
  <%= link_to q.name, products_path(tag_id: q) %>
<% end %>