config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products, only: [:show, :index, :create, :update, :destroy]
    end
  end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'
  post '/contact_submit' => 'welcome#contact_submit'

  namespace :admin do
    resources :dashboard, only: [:index]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # get '/products' => 'products#index'
  # delete '/questions/:id' => 'products#destroy'
  # get '/questions/:id/edit' => 'products#edit'
  # get '/questions/:id' => 'products#show'
  # post '/questions/:id/comments' => 'comments#create'

  get '/faq' =>'home#faq'

  # get '/admin/products' => 'admin/products#index'

  # get '/products/new'   => 'products#new', as: :new_product
  # post '/products'      => 'products#create', as: :products
  # get '/products/:id'   => 'products#show', as: :product
  # get '/products'       => 'products#index'
  #
  #
  # delete '/products/:id' => 'products#destroy'
  #
  #
  # get '/product/:id/edit' => 'products#edit', as: :edit_product
  #
  # patch '/products/:id' => 'products#update'

  resources :products, shallow: true do
    resources :reviews, only:[:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only:[:new, :create, :show]

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end


end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  has_many :reviews, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags,  through: :taggings
#################Test Driven Development Tests ####################

  validates :title, {presence: true, uniqueness: true}
  validates :price, {presence: true}
  # validates :sale_price, numericality: { less_than_or_equal_to: :price}

  before_validation(:set_sale_price)
  # before_save
  validate :sale_price_not_higher

# THIS DIDN'T WORK
  # scope :product_tag, -> (tag) do
  #   where({tag_id: tag})
  # end

  def on_sale?
    if self.sale_price < self.price
      true
    else
      false
    end
  end

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def like_for(user)
    likes.find_by(user: user)
  end

  private

  def set_sale_price
      self.sale_price ||= self.price
  end

  def sale_price_not_higher
    if self.price
      if self.sale_price > self.price
        errors.add(:sale_price, 'Sale Price cant be greater')
      end
    end
  end


########################## End Tests ##################




  # validates :title, {presence: true, uniqueness: {:case_sensitive => false}}
  # validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}
  # validates :description, {presence: true, length: {minimum: 10}}
  #
  # before_validation(:set_price)
  # before_validation(:set_hit)
  # before_validation(:set_sale_price)
  # before_save(:capitalizer)
  #
  # validate :reserved
  # validate :sale_price_not_higher
  #
  # def self.search(query)
  #   where("title ILIKE ?", "%#{query}%") |
  #   where("description ILIKE ?", "%#{query}%")
  # end
  #
  # def add_hit
  #   # obj.hit_count += 1
  #   # self.save
  #   # update_attributes({hit_count: 1})
  # # skips validation
  #   update_column(:hit_count, hit_count + 1)
  # end
  #
  # private
  #
  # def set_price
  #     self.price ||= 1
  # end
  #
  # def set_hit
  #     self.hit_count ||= 0
  # end
  #
  # def set_sale_price
  #     self.sale_price ||= self.price
  # end
  #
  # def capitalizer
  #     self.title = title.titleize
  # end
  #
  # def reserved
  #   if title.present? && title.downcase.include?('apple')
  #     errors.add(:title, 'No Apple please!')
  #   end
  #   if title.present? && title.downcase.include?('microsoft')
  #     errors.add(:title, 'No Microsoft please!')
  #   end
  #   if title.present? && title.downcase.include?('sony')
  #     errors.add(:title, 'No Sony please!')
  #   end
  # end
  #
  # def sale_price_not_higher
  #   if self.sale_price > self.price
  #     errors.add(:sale_price, 'Sale cant be greater')
  #   end
  # end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController

  PER_PAGE = 10

  def index
    current_page = params.fetch(:page, 0).to_i
    offset = PER_PAGE * current_page
    @products = Product.order(created_at: :desc).limit(PER_PAGE).offset(offset)
    @more_products = (Product.count - ((current_page + 1) * PER_PAGE)) > 0
  end

  def show
    product = Product.find params[:id]
    render json: product
  end

  def create
    product_params = params.require(:product).permit(:title, :description)
    product = Product.new product_params
    product.user = @user
    if product.save
      render json: {success: true, id: product.id}
    else
      render json: {success: false, errors: product.errors.full_messages }
    end
  end

  # def update
  #   if @product.update product_params
  #     redirect_to product_path(@product), notice: 'Product updated!'
  #   else
  #     render :edit
  #   end
  # end
  #
  # def destroy
  #   @product.destroy
  #   redirect_to products_path, notice: 'Product deleted!'
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action(:find_product, { only: [:show, :edit, :destroy, :update] })
  before_action :authorize, only: [:edit, :destroy, :update]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      ProductCreateMailer.notify_product_created(@product).deliver_later
      flash[:notice] = 'Product created successfully'
      redirect_to product_path (@product)
    else
      logger.debug "Product failed Validations".yellow
      logger.debug " - #{@product.errors.full_messages.join("\n - ")} The Product was not saved".yellow
      flash.now[:alert] = 'Please fix errors below'
      render :new
    end

  end

  def show
    @review = Review.new

    @product = Product.find params[:id]
    # @category = Category.find @product.category
    @username = User.find @product.user_id
    # new
    @tags = Tag.find @product.tag_ids
  end


  def index
    # render json:params
    if params[:tag_id]
       @tagging = Tagging.where(tag_id: params[:tag_id])
       @products_array = []
       @tagging.each do |x|
         @products_array << (x.product_id)
       end
       @products = Product.order(created_at: :desc).find(@products_array)
     else
       @products = Product.order(created_at: :desc)
     end

     #  if params[:category]
     #    @products = Product.order(created_at: :desc).where("tag = '#{params[:tag]}'")
     #  else
     #    @products = Product.order(created_at: :desc)
     #  end

     # TA CODE DIDN'T WORK
      #  @products = Product.all
      #  if params[:product_tag].present?
      #    render json:params
      #    @products = Product.all.product_tag(params[:product_tag])
      #  end
      #
  end

  def edit
    # @product = Product.find params[:id]
  end

  def update
    @product.slug = nil
    if @product.update product_params
      redirect_to product_path(@product), notice: 'Product updated!'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: 'Product deleted!'
  end


  private

  def product_params
    params.require(:product).permit([:title, :description, :price, :category, {tag_ids: []}, :tag_id, :image])
  end

  def find_product
    @product = Product.find params[:id]
  end

  def authorize
    if cannot?(:manage, @product)
      redirect_to root_path, alert: 'Not authorized!'
    end

  end

  # def rev_authorize
  #   if cannot?(:manage, @review)
  #     redirect_to root_path, alert: 'Not authorized!'
  #   end
  # end




end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/views/products/_form.html.erb
<h1>Products Form</h1>
<%= simple_form_for @product do |f| %>
  <div>
    <%= f.input :title %>
  </div>
  <div>
    <%= f.input :description %>
  </div>
  <div>
    <%= f.input :price, input_html: {:step => ".01"} %>
  </div>
  <div>
    <%= f.input :image %>
    <%# f.collection_select :category, Category.all, :id, :name  %>
  </div>
  <div>
      <%= f.association :tags, input_html: { class: 'chosen-select form-control' } %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/products/_formwithoutsimpleform.html.erb
<h1>Products Form</h1>
<p class="error_message"><%= @product.errors.full_messages.join(', ') %></p>
<%= form_for @product do |f| %>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price, :step => ".01" %>
  </div>
  <div>
    <%= f.collection_select :category, Category.all, :id, :name  %>
  </div>
  <div>
    <%= f.label :tag_ids %>
    <%= f.collection_select :tag_ids, Tag.all, :id, :name,
                            {}, { multiple: true, class: 'chosen-select' }  do |b| %>
      <div class='tag-wrapper'>
        <%= b.check_box %>
        <%= b.text %>
      </div>
      <% end  %>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/destroy.html.erb
<h1>destroyed</h1>

app/views/products/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Products</h1>
<% @products.each do |p|  %>
  <%# link_to p.title, p %>
    <%= image_tag p.image.url(:thumb) if p.image.present? %>
  <% @username = User.find p.user_id %>
  <%= @username.first_name %>
  <%= link_to p.title, product_path(p) %>
  <% if user_signed_in? && can?(:like, p) %>
    <% if p.liked_by?(current_user)  %>
      <%= link_to '<i class="fa fa-thumbs-down" aria-hidden="true" style="color: red"></i>'.html_safe, like_path(p.like_for(current_user)), method: :delete %>
    <% else  %>
      <%= link_to '<i class="fa fa-thumbs-up" aria-hidden="true"></i>'.html_safe, product_likes_path(p), method: :post %>
    <% end  %>
  <% end  %>
  <%= pluralize p.likes.count, 'like' %>
  <hr>
<% end  %>

app/views/products/new.html.erb
<h1>New</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1>Show Product</h1>
<h1>Product title -><%= @product.title %></h1>
<% if user_signed_in? && can?(:like, @product) %>
  <% if @product.liked_by?(current_user)  %>
    <%= link_to '<i class="fa fa-thumbs-down" aria-hidden="true" style="color: red"></i>'.html_safe, like_path(@product.like_for(current_user)), method: :delete %>
  <% else  %>
    <%= link_to '<i class="fa fa-thumbs-up" aria-hidden="true"></i>'.html_safe, product_likes_path(@product), method: :post %>
  <% end  %>
<% end  %>
<p> Description -> <%= @product.description %></p>
<p> Price -> $<%= @product.price %></p>
<p> Sale Price -> <%= number_to_currency(@product.sale_price) %></p>
<p>Creator -> <%= @username.first_name %></p>

<!--<p>Category -> <%# @category.name %></p>-->

<br>
<% if can?(:manage, @product) %>
  <%= link_to 'Edit', edit_product_path(@product) %>
  <%= link_to 'Delete', product_path(@product), method: :delete,
  data: { confirm: 'Are you sure?' } %>
<% end  %>

  <%= image_tag @product.image.url if @product.image.present?%>


<h1>TAGS</h1>
  <% @tags.each do |tag| %>
    <%= tag.name %>
  <% end %>

<hr>
<h2>Reviews</h2>
<h3>Create new review</h3>

<!-- We don't need this anymore with simpleform 👇 -->
<%# @review.errors.full_messages.join(',') %>
<%= simple_form_for [@product, @review] do |f| %>
<%= f.input :body %>
<%= f.input :rating %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

<hr>


<% @product.reviews.each do |review| %>
<%  @username = User.find review.user_id %>

    Review written by this douche:  <%= @username.first_name %>
    <%= review.body %>
    <%= review.rating %>

  <% if can?(:manage, review) %>
    <%= link_to 'delete', review_path(review), method: :delete, data:{ confirm: 'Are You Sure?'}  %>
  <% end  %>

    <hr>
<% end  %>