config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products, only: [:show, :index, :create, :update, :destroy]
    end
  end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'
  post '/contact_submit' => 'welcome#contact_submit'

  namespace :admin do
    resources :dashboard, only: [:index]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # get '/products' => 'products#index'
  # delete '/questions/:id' => 'products#destroy'
  # get '/questions/:id/edit' => 'products#edit'
  # get '/questions/:id' => 'products#show'
  # post '/questions/:id/comments' => 'comments#create'

  get '/faq' =>'home#faq'

  # get '/admin/products' => 'admin/products#index'

  # get '/products/new'   => 'products#new', as: :new_product
  # post '/products'      => 'products#create', as: :products
  # get '/products/:id'   => 'products#show', as: :product
  # get '/products'       => 'products#index'
  #
  #
  # delete '/products/:id' => 'products#destroy'
  #
  #
  # get '/product/:id/edit' => 'products#edit', as: :edit_product
  #
  # patch '/products/:id' => 'products#update'

  resources :products, shallow: true do
    resources :reviews, only:[:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only:[:new, :create, :show]

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
     user ||= User.new # guest user (not logged in)

     if user.is_admin?
       can :manage, :all
     end

    can :manage, Product do |p|
      p.user == user
    end

    can :manage, Review do |r|
      r.user == user
    end

    cannot :like, Product do |p|
      p.user == user
    end

    can :like, Product do |p|
      p.user != user
    end

    



    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, {presence: true, uniqueness: true}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :product_id, uniqueness: {scope: :user_id}
end

app/models/location.rb
class Location < ApplicationRecord
 belongs_to :user

 geocoded_by :ip_address
 after_validation :geocode

 validates :user_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  has_many :reviews, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags,  through: :taggings
#################Test Driven Development Tests ####################

  validates :title, {presence: true, uniqueness: true}
  validates :price, {presence: true}
  # validates :sale_price, numericality: { less_than_or_equal_to: :price}

  before_validation(:set_sale_price)
  # before_save
  validate :sale_price_not_higher

# THIS DIDN'T WORK
  # scope :product_tag, -> (tag) do
  #   where({tag_id: tag})
  # end

  def on_sale?
    if self.sale_price < self.price
      true
    else
      false
    end
  end

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def like_for(user)
    likes.find_by(user: user)
  end

  private

  def set_sale_price
      self.sale_price ||= self.price
  end

  def sale_price_not_higher
    if self.price
      if self.sale_price > self.price
        errors.add(:sale_price, 'Sale Price cant be greater')
      end
    end
  end


########################## End Tests ##################




  # validates :title, {presence: true, uniqueness: {:case_sensitive => false}}
  # validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}
  # validates :description, {presence: true, length: {minimum: 10}}
  #
  # before_validation(:set_price)
  # before_validation(:set_hit)
  # before_validation(:set_sale_price)
  # before_save(:capitalizer)
  #
  # validate :reserved
  # validate :sale_price_not_higher
  #
  # def self.search(query)
  #   where("title ILIKE ?", "%#{query}%") |
  #   where("description ILIKE ?", "%#{query}%")
  # end
  #
  # def add_hit
  #   # obj.hit_count += 1
  #   # self.save
  #   # update_attributes({hit_count: 1})
  # # skips validation
  #   update_column(:hit_count, hit_count + 1)
  # end
  #
  # private
  #
  # def set_price
  #     self.price ||= 1
  # end
  #
  # def set_hit
  #     self.hit_count ||= 0
  # end
  #
  # def set_sale_price
  #     self.sale_price ||= self.price
  # end
  #
  # def capitalizer
  #     self.title = title.titleize
  # end
  #
  # def reserved
  #   if title.present? && title.downcase.include?('apple')
  #     errors.add(:title, 'No Apple please!')
  #   end
  #   if title.present? && title.downcase.include?('microsoft')
  #     errors.add(:title, 'No Microsoft please!')
  #   end
  #   if title.present? && title.downcase.include?('sony')
  #     errors.add(:title, 'No Sony please!')
  #   end
  # end
  #
  # def sale_price_not_higher
  #   if self.sale_price > self.price
  #     errors.add(:sale_price, 'Sale cant be greater')
  #   end
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :rating, {presence: true, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to:5}}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :products, through: :taggings

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :nullify
  has_many :reviews, dependent: :nullify
  
  has_many :locations, dependent: :nullify

  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :product
  before_create :generate_api_key

  geocoded_by :address
  after_validation :geocode

  has_secure_password


  def self.search(query)
    where("first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end


  before_validation :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  # in console -> VALID_EMAIL_REGEX.match('abc@abc.com') ->returns match data
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}".strip.titleize
  end

  private

  def downcase_email
    self.email&.downcase!
  end

  def generate_api_key
    loop do
      self.api_key = SecureRandom.hex
      break unless User.exists?(api_key: api_key)
    end
  end





end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def faq

  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon ADMIN</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
  </head>

  <body>
      <a href="/">Home</a>
      <%= link_to('Contact Us', contact_path) %>
      <%= link_to('About', about_path) %>
      <% if user_signed_in?  %>
          <span>You're signed in <%= session[:user_id] %></span>
           <span>Hello <%= current_user.full_name %>, </span>
            <%= link_to 'Sign Out', sessions_path, method: :delete %>
        <% else %>
          <span>You're not signed in</span>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign In', new_session_path %>

          <% end %>


<div style="text-align:center">
      <%= notice || alert %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyBc2C0i-MdL0MaUBZ-_lfBFTXQaqqZTAkA"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  <body>
      <a href="/">Home</a>
      <%= link_to('Contact Us', contact_path) %>
      <%= link_to('About', about_path) %>
      <% if user_signed_in?  %>
          <span>You're signed in <%= session[:user_id] %></span>
           <span>Hello <%= current_user.full_name %>, </span>
            <%= link_to 'Sign Out', sessions_path, method: :delete %>
        <% else %>
          <span>You're not signed in</span>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign In', new_session_path %>

          <% end %>


<div style="text-align:center">
      <%= notice || alert %>
    <%= yield %>
    </div>
  </body>
</html>